### ISSUE TITLE
Issues with "Reboot Later"

### ISSUE THREAD

**Issue by azulskyknight** [amidaware/tacticalrmm#1174]
**Server Info (please complete the following information):**
 - OS: [Ubuntu 20.04 LTS and Debian 11.3]
 - Browser: [Firefox 101.0.1 64bit, Chrome 102.5005.115 64bit, New Edge 102.0.1245.39 64bit ]
 - RMM Version (as shown in top left of web UI): v0.13.4

**Installation Method:**
  - [X] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI): v2.0.4
- Agent OS: Windows 10 v21H1, Windows 10 v21H2, Windows Server 2016 and 2019

**Describe the bug**
Firefox displays a different UI tool to select the date time stamp passed for the scheduled reboot.  Firefox only shows the calendar portion, no time selector is available.  

If a reboot is scheduled for a time that has already passed, a 400 timeout error is returned.  This may be intentional, but seems like it should be handled a little more gracefully.

During the scheduling process, if any of the elements are typed in manually the scheduling event returns a 400 invalid date error.  

If on Firefox, once this corruption is revealed the only way to clear it is to refresh the browser and try again without actually typing anything in.  Which limits the user to changing the date alone.  

If on a Chromium browser the mangled date time can be fixed by clicking the day on the calendar intended.  If a manual date is typed in, both today and that date will be selected on the calendar, and clicking the correct day will result in a working time stamp that successfully schedules.  

On both browsers if the seconds value on the time is reduced to 00, it will simply vanish once a date is chosen on the calendar.  Firefox doesn't display the time selector tools at all and will return an invalid date error when such a shortened timestamp is used.  Chromium based browsers lose the seconds column in the time selector portion of the UI but seem to schedule properly assuming a date is selected on the calendar as a final action first. 

**To Reproduce**
1. Click an agent
2. right click, reboot -> later
3. Type values into the date and time fields. (without using the UI)
4. Click Schedule Reboot

(See above for using the UI to "fix" things)

**Expected behavior**
I expect to be able to type in a proper date / time string, or select one from the UI and have it work the first time.  It would also be nice if I could copy / paste the entire date time string into the reboot time box so I can rapidly schedule multiple reboots quickly.

**Screenshots**
![image](https://user-images.githubusercontent.com/45128329/173930177-0863e3d1-6871-4d5e-82b9-07badc7d4194.png)
![image](https://user-images.githubusercontent.com/45128329/173930230-51d7f964-cbd2-4c9c-82a0-c4ed80a999b8.png)
![image](https://user-images.githubusercontent.com/45128329/173930417-3637856a-bbc1-47f5-a200-ad87e05f2c87.png)
![image](https://user-images.githubusercontent.com/45128329/173930464-f6583433-4629-4293-a7a0-e9bc8d90b4cc.png)

**Additional context**
Silversword was assisting me (AzulSkyknight) in #Support on Discord, searching for myself for comments from today 6-15-2022 around 9am Arizona time will find the conversation.

**Comment by eCloudJTuttle** [comment]
Using chrome developer tools to inspect the patch command, the date/time being passed is invalid format.
![image](https://user-images.githubusercontent.com/91274775/178503468-3b48d80b-4a50-4840-900a-7ec01a0b1d92.png)

**Comment by wh1te909** [comment]
I have fixed the 400 timeout error when date is in past in e8e19fede742f6f938dbcf7326bbefe0d05fe994 (this was actually causing the agent to crash LOL which is why the timeout). 

As for the invalid date issue, I am having a hard time reproducing it, I have tried typing the values by hand instead of using the GUI but don't get any errors. Only time I get error is if I type an invalid year. Any way to record a GIF or video of how to consistently reproduce? Thanks.

**Comment by eCloudJTuttle** [comment]
I can also confirm that the issue has gone away in chrome.

**Comment by azulskyknight** [comment]
Issue still exists, at least in small part.

There are circumstances I cannot fully duplicate with New Edge and Firefox where the time field doesn't contain seconds.  The UI is passing a timestamp missing those digits, instead of as zeros.  As a result, invalid timestamp and 400 error.

**Comment by wh1te909** [comment]
Fixed (again lol) in Release 0.14.6

**Comment by JSuenram** [comment]
Same issue here in v0.15.7, did not test in v0.15.9...

**Comment by silversword411** [comment]
Maybe reboot has the same logic problem as https://github.com/amidaware/tacticalrmm/commit/9f95c57a0972fff1ff660c7a2a77be6bb04a23cd ?
